### ISSUE TITLE
Created an admin view for Categories and Groups

### ISSUE THREAD

**Issue by jonquet** [ontoportal/ontoportal_web_ui#2]
### Issue
There is currently no graphic way to edit/create Categories and Views in OntoPortal.
It has to be done via the API calls (PATCH, PUT, DELETE) on the respective endpoints: 
http://data.agroportal.lirmm.fr/categories
http://data.agroportal.lirmm.fr/groups

### Proposition 
Create a page in the Administration section to edit/create Categories and Views (similar to what we have for "Ontology administration" or on AgroPortal for "User Administration").

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7379183/210210674-fa70350e-fc6a-42bc-be5c-be5644336fb9.png">

Related to this is #1 which concerns the creation of a modal to simply view the Categories and Groups.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/agroportal/project-management/issues/422, move this issue to be ready to be merged state.
