### ISSUE TITLE
Detach from ncbo/bioportal_web_ui fork

### ISSUE THREAD

**Issue by jvendetti** [ontoportal/ontoportal_web_ui#9]
Currently, this repository is a fork of `ncbo/bioportal_web_ui`. There's an effort underway to make the ontoportal organization the centralized location for the OntoPortal code base, rather than the ncbo organization. See https://github.com/ontoportal/ontoportal-project/issues/6 for more details.

Detachment can be requested via [GitHub Support](https://support.github.com/request/fork).

**Comment by jvendetti** [comment]
@syphax-bouazzouni - I want to verify I'm doing the right / desired thing here. I assume that "Extract" is the correct operation. Do you agree?
<br>
<img width="1007" alt="Screen Shot 2023-05-23 at 11 51 06 AM" src="https://github.com/ontoportal/ontoportal_web_ui/assets/1696923/3bfe854b-deef-43aa-8bc8-827f61f92671">

**Comment by syphax-bouazzouni** [comment]
Hi @jvendetti, 
I don't advise you to use the virtual agent.

But instead directly write your request, to one of the support team members (that responds generally fast). Where you give clear requirements of what you want: make `ncbo/bioportal_web_ui` repository a fork of `ontoportal/ontoportal_web_ui`

(it will be too risky to do it by the bot, and those `Detach` and `Extract` are not really clear)

Below is the message that I wrote for Agroportal as example

```
Hi,
Can you reroute the following forks?

https://github.com/ontoportal-lirmm/bioportal_web_ui to https://github.com/ontoportal/ontoportal_web_ui

https://github.com/ontoportal-lirmm/goo to https://github.com/ontoportal/goo

https://github.com/ontoportal-lirmm/ontologies_linked_data to https://github.com/ontoportal/ontologies_linked_data

https://github.com/ontoportal-lirmm/ontologies_api to https://github.com/ontoportal/ontologies_api

https://github.com/ontoportal-lirmm/ontologies_api_ruby_client to https://github.com/ontoportal/ontologies_api_ruby_client

https://github.com/ontoportal-lirmm/ncbo_cron to https://github.com/ontoportal/ncbo_cron

https://github.com/ontoportal-lirmm/sparql-client to https://github.com/ontoportal/sparql-client

https://github.com/ontoportal-lirmm/ncbo_annotator to https://github.com/ontoportal/ncbo_annotator

Thanks,
```

**Comment by jvendetti** [comment]
OK - I took your advice and entered a support request instead of using the agent. This was the text of the request:

> Hello GitHub Support. I'm wondering if you could assist me with changing an upstream repository to a fork?
> 
> Currently ontoportal/ontoportal_web_ui is a fork of ncbo/bioportal_web_ui.
> 
> I would like to reverse this arrangement so that ncbo/bioportal_web_ui is a fork of ontoportal/ontoportal_web_ui.
> 
> Or - to say it another way - I would like to detach the fork ontoportal/ontoportal_web_ui from ncbo/bioportal_web_ui. Then I would like to attach ncbo/bioportal_web_ui as a fork of ontoportal/ontoportal_web_ui.
> 
> Please note that I'd like to leave the [existing forks](https://github.com/ontoportal/ontoportal_web_ui/forks) of ontoportal/ontoportal_web_ui attached/undisturbed

**Comment by jvendetti** [comment]
GitHub Support has completed implementing the request, and `ncbo/bioportal_web_ui` is now a fork of `ontoportal/ontoportal_web_ui`. 

I believe however, that there was one unintended consequence of this process. There were a couple of forks of `ncbo/bioportal_web_ui` from alexskr and RobertCoop that got re-routed to `ontportal/ontoportal_web_ui`. This might require another support issue to re-route those forks back to `ncbo/bioportal_web_ui`.

![Screen Shot 2023-05-24 at 9 34 00 AM](https://github.com/ontoportal/ontoportal_web_ui/assets/1696923/102448a3-1863-4957-bcfd-d7254b93a425)

**Comment by syphax-bouazzouni** [comment]
Great thanks for the work done
